---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.


<<<<<<< HEAD


=======
This is a line from RStudio - Ryan

Ryan's experience:

  **12.1**: Encountered no problems, already had Git installed on my machine and GitHub connected to RStudio.
  
  **12.2**: GitHub repo was already created, we just needed everyone to access it.
  
  **12.3**: Encountered no problems.
  
  **12.4**: Committed the line from RStudio into the Github repo successfully.

This is a line from RStudio - John

John's Experience:

  **12.1**: No problems, I already had GitHub and RStudio
  
  **12.2**: No problems, everyone had the same issue where only one person could join each team
  
  **12.3**: No problems, although I redid this step to get the repository in my class folder
  
  **12.4**: It said there were unresolved merge conflicts when I committed, although it was easily fixable
  
  **12.5**: I was able to successfully merge everything together in RStudio and push an updated version to GitHub
  
  **12.6**: All lines showed up in GitHub

Zane's Experience:

  **12.1**: No problems, I already had a git account and had R and RStudio installed.
  
  **12.2**: No problems, this step was mostly done by the instructor. The whole class ran into an issue where the teams could only have 1 person, but the instructor fixed it very quickly.
  
  **12.3**: No problems, the instructions were very thorough and helpful.
  
  **12.4**: This is a line from RStudio. Commit test. I ran into an issue where I forgot my github account password, and had to reset it. Now it isn't letting me save my file, pull, push, or commit. I used task manager to close and restart RStudio and will try to commit again. It seems to be working now, but I am now finding merge conflict issues due to Ryan's commit. RStudio is being remarkably unhelpful with telling me how to resolve them. I think staging my changes worked, we'll see though.
  
  
  This is a line from RStudio - Amanda
  I had to run the user name and email lines to make commit work from my RStudio.

>>>>>>> 061a3bfcd6dcd3c710d942a77650d40d2cb21744
